# Generated by Django 3.2 on 2022-05-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='edition',
            field=models.CharField(choices=[('FD', 'FIRST EDITION'), ('SD', 'SECOND EDITION'), ('TD', 'THIRD EDITION')], max_length=2),
        ),
    ]
