# Generated by Django 3.2 on 2022-05-20 01:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7de37909-eec9-48d3-bcb3-5ab3c863dfec')),
        ),
    ]
