# Generated by Django 3.2 on 2022-05-20 01:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0002_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('43f2dd94-7364-445c-ad4a-1f271fed30bb')),
        ),
    ]
