# Generated by Django 3.2 on 2022-05-20 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0003_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e1b31a44-1386-4d98-a1f7-605184dcecbe')),
        ),
    ]
