# Generated by Django 3.2 on 2022-05-20 01:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_alter_category_edition'),
        ('location_app', '0004_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c12026bd-ebab-421d-ace5-8c8784241ffa')),
        ),
        migrations.CreateModel(
            name='RackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_app.rack')),
            ],
        ),
    ]
