# Generated by Django 3.2 on 2022-05-20 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0005_auto_20220519_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='status',
            new_name='available',
        ),
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ae54007c-3849-402e-b028-bdd67cda2b60')),
        ),
    ]
