# Generated by Django 3.2 on 2022-05-20 02:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0006_auto_20220519_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f7e73f1c-2eea-42cf-acbe-ad444f47626a')),
        ),
    ]
