# Generated by Django 3.2 on 2022-05-20 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0007_auto_20220519_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('db9514d4-2dd0-40c2-a0b5-f48f7ffb3546')),
        ),
    ]
