# Generated by Django 3.2 on 2022-05-20 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0008_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('855c078d-d3b0-4616-8e49-d951579b9a7c')),
        ),
    ]
