# Generated by Django 3.2 on 2022-05-20 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0009_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5e7b4c24-d5ed-46f1-8488-69e4864b8798')),
        ),
    ]
