# Generated by Django 3.2 on 2022-05-20 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0010_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('335b1fde-1cce-4d32-9fcc-d3c458ba2212')),
        ),
    ]
