# Generated by Django 3.2 on 2022-05-20 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0011_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('671a3138-b54b-4dfa-b1fe-958685335bb8')),
        ),
    ]
