# Generated by Django 3.2 on 2022-05-20 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0012_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1a7bfb44-cc6c-4ed4-a3db-8fd43c22b2e3')),
        ),
    ]
