# Generated by Django 3.2 on 2022-05-20 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0015_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2410014f-a2dd-4995-be04-5fad49bf0a1d')),
        ),
    ]
