# Generated by Django 3.2 on 2022-05-21 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0017_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d2f42bd6-efb9-4c34-8853-3e5392edf923')),
        ),
    ]
