# Generated by Django 3.2 on 2022-05-21 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0018_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1ee83145-fbc1-45e3-b622-593d516d7dcb')),
        ),
    ]
