# Generated by Django 3.2 on 2022-05-21 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0019_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d572c5d2-08f9-4bdb-901a-cb783def54a6')),
        ),
    ]
