# Generated by Django 3.2 on 2022-05-22 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0020_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5b009590-2aa4-49b3-adce-09135b10dfeb')),
        ),
    ]
