# Generated by Django 3.2 on 2022-05-22 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0021_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f3abb95f-f0e2-4f65-9a0a-5a4fea6dd570')),
        ),
    ]
