# Generated by Django 3.2 on 2022-05-22 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0022_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0dcdc278-7842-4a1c-884f-a10367a930ce')),
        ),
    ]
